apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pocdapr-secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/dapr-secrets.json
  - name: nestedSeparator
    value: ":"
